### ISSUE TITLE
Repl support update

### ISSUE THREAD

**Issue by maks** [scidart/scidart.org#8]
I posted a [comment](https://github.com/BlackHC/dart_repl/issues/5#issuecomment-758510313) with a small gist a I did showing how to use the vm_service package with current version of Dart, so hopefully the author of the the dart_repl package or maybe someone else will be able to get it updated to work with current versions of Dart.

**Comment by polotto** [comment]
That's amazing!!! Do you want to help SciDart with REPL? I can create a separated repository for that project, so you can work  focused only in REPL.

**Comment by maks** [comment]
@polotto I'd like to but unfortunately I'm in the middle of another project at the moment. I only needed a very basic repl for the project I'm working on hence the code in the gist I posted. I noticed that the author of the repl package has assigned himself to that issue so he maybe working on updating the package himself. If not, I may have time later on to come back and work on updating that repl package based on code in my gist.

**Comment by polotto** [comment]
I sent an email to the author a long time ago. Until I now, he don't have interest to keep his project updated and working, because that, I asked to him to work in a separated version and He allow me to do that. I didn't start yet because I'm working in SciDart Plot package but the REPL is the next thing in my list.

**Comment by polotto** [comment]
@maks I studied all the articles related to Dart REPL, Dart Playground and I made my decision: I'll build a small Dart interpreter. My main goal is run SciDart everywhere in interactive way, including Web, the Dart_VM REPL and Dart Playground always rely on some cloud machine with Dart VM installed. if you are interest in help me, just open issue here: https://github.com/scidart/scidart_dart_interpreter
